cmake_minimum_required(VERSION 4.1)
project(C C)

set(CMAKE_C_STANDARD 11)

add_executable(C
        "2025/2s/Estruturas de dados/Filas/ex01.c"
        "2025/2s/Estruturas de dados/Listas Encadeadas/ex01.c"
        "2025/2s/Estruturas de dados/Listas Encadeadas/ex02.c"
        "2025/2s/Estruturas de dados/Pilhas/ex01.c"
        "2025/2s/Estruturas de dados/Recursividade/ex01.c"
        "2025/2s/Estruturas de dados/Recursividade/ex02.c"
        "2025/2s/Estruturas de dados/Recursividade/ex03.c"
        "2025/2s/Estruturas de dados/Recursividade/ex04.c"
        "2025/2s/Estruturas de dados/Recursividade/ex05.c"
        2025/2s/Exercícios/exerciciosPropostos01/ex01.c
        2025/2s/Exercícios/exerciciosPropostos01/ex02.c
        2025/2s/Exercícios/exerciciosPropostos01/ex03.c
        2025/2s/Exercícios/exerciciosPropostos01/ex04.c
        2025/2s/Exercícios/exerciciosPropostos02/ex01.c
        2025/2s/Exercícios/exerciciosPropostos02/ex02.c
        2025/2s/Exercícios/exerciciosPropostos02/ex03.c
        2025/2s/Exercícios/exerciciosPropostos02/ex04.c
        2025/2s/Exercícios/exerciciosPropostos02/ex05.c
        2025/2s/Exercícios/exerciciosPropostos03/ex01.c
        2025/2s/Exercícios/exerciciosPropostos03/ex01Answer.c
        2025/2s/Exercícios/exerciciosPropostos03/ex02.c
        2025/2s/Exercícios/exerciciosPropostos03/ex03.c
        2025/2s/Exercícios/exerciciosPropostos03/ex04.c
        2025/2s/Exercícios/exerciciosPropostos03/ex05.c
        2025/2s/Exercícios/exerciciosPropostos04/ex01.c
        2025/2s/Exercícios/exerciciosPropostos04/ex02.c
        2025/2s/Exercícios/exerciciosPropostos08/exFuncoes.c
        2025/2s/Exercícios/exercíciosPropostos09/structs.c
        2026/ERD/P1/Lista_Simplesmente_Encadeada/ex01.c)
